# -*- coding: utf-8 -*-
"""VLM_CH3_2nd_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewQXc_T0rJTVLWMRWIKT2vMufzrM74GV

# VLM, Chapter three, second notebook: Inference Notebook
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import os, re
# if "COLAB_" not in "".join(os.environ.keys()):
#     !pip install unsloth
# else:
#     # Do this only in Colab notebooks! Otherwise use pip install unsloth
#     import torch; v = re.match(r"[0-9\.]{3,}", str(torch.__version__)).group(0)
#     xformers = "xformers==" + ("0.0.32.post2" if v == "2.8.0" else "0.0.29.post3")
#     !pip install --no-deps bitsandbytes accelerate {xformers} peft trl triton cut_cross_entropy unsloth_zoo
#     !pip install sentencepiece protobuf "datasets>=3.4.1,<4.0.0" "huggingface_hub>=0.34.0" hf_transfer
#     !pip install --no-deps unsloth
# !pip install transformers==4.55.4
# !pip install --no-deps trl==0.22.2

from unsloth import FastVisionModel # FastLanguageModel for LLMs
import torch

model, processor = FastVisionModel.from_pretrained(
    # My published model on Huggingface in address: https://huggingface.co/Rahimsa/lora_model_Ch3
    "Rahimsa/lora_model_Ch3",
    load_in_4bit=True,
)

from unsloth import FastVisionModel, get_chat_template

processor = get_chat_template(processor, "gemma-3")

FastVisionModel.for_inference(model)

# Load TEST dataset, not training data. From test split

from datasets import load_dataset

test_dataset = load_dataset("unsloth/LaTeX_OCR", split="test")

# Select 3 images from test set
test_indices = [0, 5, 10]  # Choose any 3 indices
test_samples = [test_dataset[i] for i in test_indices]

print(f"Loaded {len(test_samples)} test images")

def predict_latex(image):
    instruction = "Write the LaTeX representation for this image."

    messages = [
        {
            "role": "user",
            "content": [{"type": "image"}, {"type": "text", "text": instruction}],
        }
    ]

    input_text = processor.apply_chat_template(messages, add_generation_prompt=True)
    inputs = processor(
        image,
        input_text,
        add_special_tokens=False,
        return_tensors="pt",
    ).to("cuda")

    outputs = model.generate(
        **inputs,
        max_new_tokens=128,
        use_cache=True,
        temperature=1.0,
        top_p=0.95,
        top_k=64
    )

    # Decode output
    generated_text = processor.tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract LaTeX (remove instruction part)
    latex_output = generated_text.split("assistant")[-1].strip() if "assistant" in generated_text else generated_text

    return latex_output

# display results

import matplotlib.pyplot as plt
from IPython.display import display, Math

for idx, sample in enumerate(test_samples):
    print(f"\n{'='*60}")
    print(f"Test Image {idx+1}")
    print(f"{'='*60}")

    image = sample["image"]
    ground_truth = sample["text"]

    # Predict
    predicted_latex = predict_latex(image)

    # Display image and results side by side
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    # Show image
    axes[0].imshow(image)
    axes[0].set_title(f"Test Image {idx+1}")
    axes[0].axis('off')

    # Show text results
    axes[1].text(0.1, 0.7, f"Ground Truth:\n{ground_truth}",
                fontsize=10, verticalalignment='top', wrap=True)
    axes[1].text(0.1, 0.3, f"Predicted:\n{predicted_latex}",
                fontsize=10, verticalalignment='top', wrap=True, color='blue')
    axes[1].axis('off')
    axes[1].set_title("LaTeX Results")

    plt.tight_layout()
    plt.show()

    # Render LaTeX
    print("\nRendered Ground Truth:")
    try:
        display(Math(ground_truth))
    except:
        print("Could not render ground truth LaTeX")

    print("\nRendered Prediction:")
    try:
        display(Math(predicted_latex))
    except:
        print("Could not render predicted LaTeX")

print(f"\n{'='*60}")
print("Inference completed on 3 test images!")
print(f"{'='*60}")