
"""VLM_Final_Project_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoBfGwZcAFVf3c8ElEgIKALD6DZyj52D

# VLM, Final Project: Simple Multimodal RAG

# Used paper:
Attention Is All You Need
https://arxiv.org/pdf/1706.03762