# -*- coding: utf-8 -*-
"""VLM_Ch2_Pra_2_Captioning_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmD5vglQfJ7vIWrsRrN4hex6giueRV4R

# Chapter two, Practice Tow: Image Captioning

## import librarys
"""

pip install -q git+https://github.com/huggingface/transformers accelerate

# It's highly recommanded to use `[decord]` feature for faster video loading.
!pip install -q qwen-vl-utils[decord]==0.0.8

import torch
from PIL import Image
from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info
import csv
import os
from pathlib import Path

MID = "Qwen/Qwen2.5-VL-3B-Instruct"