# -*- coding: utf-8 -*-
"""VLM_Ch4_Book_Title.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5UjKlfQR2oSVUxhTwgSOeKIpQx9SrwF

# Chapter four, mini project:
Persian Book Cover Title Recognition using Vision-Language Models

Fine-tuning VLM to extract Persian book titles from cover images
