# -*- coding: utf-8 -*-
"""VLM_Ch2_mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sugz6CuE5KaMsHhHiIMyA9icuc2paBEs

## Chapter two, mini Project
"""

import torch
from transformers import CLIPProcessor, CLIPModel
import pandas as pd
from PIL import Image
import numpy as np
import os

# Setting
device = "cuda" if torch.cuda.is_available() else "cpu"
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(device)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# Global variables
image_embeddings = None
image_names = None
captions = None

# Functions

# Split text into chunks
def chunk_text(text, max_words=15):
    words = text.split()
    return [' '.join(words[i:i + max_words])
            for i in range(0, len(words), max_words)]

# Encode text with chunking support
def encode_text(text):
    chunks = chunk_text(text)

    if len(chunks) == 1:
        inputs = processor(text=[text], return_tensors="pt",
                          padding=True, truncation=True).to(device)
        with torch.no_grad():
            return model.get_text_features(**inputs)
    else:
        chunk_embeddings = []
        for chunk in chunks:
            inputs = processor(text=[chunk], return_tensors="pt",
                             padding=True, truncation=True).to(device)
            with torch.no_grad():
                emb = model.get_text_features(**inputs)
                chunk_embeddings.append(emb)

        return torch.mean(torch.stack(chunk_embeddings), dim=0)

#Encode single image
def encode_image(image_path):
    image = Image.open(image_path).convert('RGB')
    inputs = processor(images=image, return_tensors="pt").to(device)

    with torch.no_grad():
        return model.get_image_features(**inputs)

# Build image embeddings database
def build_index(csv_path, image_folder):
    global image_embeddings, image_names, captions

    print("Building image embeddings index...")

    df = pd.read_csv(csv_path)

    print(f"Available columns: {df.columns.tolist()}")
    print(f"DataFrame shape: {df.shape}\n")

    # Using some columns
    image_names = df['image_name'].tolist()
    captions = df['english_caption'].tolist()

    embeddings_list = []
    valid_indices = []

    for idx, image_name in enumerate(image_names):
        image_path = os.path.join(image_folder, image_name)

        if not os.path.exists(image_path):
            print(f"Warning: {image_path} not found, skipping...")
            continue

        try:
            emb = encode_image(image_path)
            embeddings_list.append(emb.cpu())
            valid_indices.append(idx)

            if len(embeddings_list) % 10 == 0:
                print(f"Processed {len(embeddings_list)}/{len(image_names)} images")
        except Exception as e:
            print(f"Error processing {image_name}: {e}")
            continue

    # Keeping success images
    image_names = [image_names[i] for i in valid_indices]
    captions = [captions[i] for i in valid_indices]

    image_embeddings = torch.cat(embeddings_list, dim=0)
    print(f"\nIndex built successfully with {len(embeddings_list)} images\n")

# Search by text query
def search_by_text(query_text, top_k=5):
    """Search images using text query"""
    if image_embeddings is None:
        raise ValueError("Index not built. Call build_index() first.")

    # Encode query text
    text_emb = encode_text(query_text)

    # Normalize embeddings for cosine similarity
    text_emb = text_emb / text_emb.norm(dim=-1, keepdim=True)
    img_emb_normalized = image_embeddings / image_embeddings.norm(dim=-1, keepdim=True)

    # Calculate similarity
    similarities = (text_emb @ img_emb_normalized.T).squeeze(0)

    # Get top-k results
    top_k = min(top_k, len(similarities))
    top_indices = torch.topk(similarities, top_k).indices.cpu().numpy()
    top_scores = torch.topk(similarities, top_k).values.cpu().numpy()

    results = [(image_names[idx], float(top_scores[i]))
               for i, idx in enumerate(top_indices)]

    return results

# Search by image query
def search_by_image(query_image_path, top_k=5):
    """Search similar images using an image query"""
    if image_embeddings is None:
        raise ValueError("Index not built. Call build_index() first.")

    # Encode query image
    query_emb = encode_image(query_image_path).cpu()

    # Normalize embeddings
    query_emb = query_emb / query_emb.norm(dim=-1, keepdim=True)
    img_emb_normalized = image_embeddings / image_embeddings.norm(dim=-1, keepdim=True)

    # Calculate similarity
    similarities = (query_emb @ img_emb_normalized.T).squeeze(0)

    # Get top-k results (skip the first one if it's the same image)
    top_k_fetch = min(top_k + 1, len(similarities))
    top_indices = torch.topk(similarities, top_k_fetch).indices.cpu().numpy()
    top_scores = torch.topk(similarities, top_k_fetch).values.cpu().numpy()

    # Filter out exact match
    query_name = os.path.basename(query_image_path)
    results = []
    for i, idx in enumerate(top_indices):
        if image_names[idx] != query_name or len(results) == 0:
            results.append((image_names[idx], float(top_scores[i])))
        if len(results) == top_k:
            break

    return results

# Evaluation with random samples
def evaluate_system(num_samples=5):
    if image_embeddings is None:
        raise ValueError("Index not built.")

    print("="*60)
    print("EVALUATION: Text-to-Image Search")
    print("="*60)

    # Sample some captions for text search
    sample_indices = np.random.choice(len(captions),
                                     min(num_samples, len(captions)),
                                     replace=False)

    for idx in sample_indices:
        caption = captions[idx]
        true_image = image_names[idx]

        print(f"\nQuery: '{caption[:100]}...'")
        print(f"Ground truth: {true_image}")

        results = search_by_text(caption, top_k=3)
        print("Top 3 results:")
        for rank, (img, score) in enumerate(results, 1):
            marker = "[MATCH]" if img == true_image else "       "
            print(f"  {marker} {rank}. {img} (score: {score:.4f})")

def display_results(query, results, image_folder):
    """Display search results visually"""
    import matplotlib.pyplot as plt

    if not results:
        print("No results to display")
        return

    fig, axes = plt.subplots(1, len(results) + 1, figsize=(15, 3))

    # Ensure axes is iterable
    if len(results) == 0:
        axes = [axes]

    # Show query
    if isinstance(query, str) and not query.endswith(('.jpg', '.png', '.jpeg')):
        axes[0].text(0.5, 0.5, f"Query:\n{query[:50]}...",
                     ha='center', va='center', wrap=True)
        axes[0].axis('off')
        axes[0].set_title("Text Query")
    else:
        img = Image.open(query)
        axes[0].imshow(img)
        axes[0].axis('off')
        axes[0].set_title("Query Image")

    # Show results
    for idx, (img_name, score) in enumerate(results, 1):
        img_path = os.path.join(image_folder, img_name)
        img = Image.open(img_path)
        axes[idx].imshow(img)
        axes[idx].axis('off')
        axes[idx].set_title(f"{img_name}\n{score:.3f}")

    plt.tight_layout()
    plt.show()

# Using images and csv files from google colab
CSV_PATH = "/content/captions.csv"
IMAGE_FOLDER = "/content/images"

# Making an index
build_index(CSV_PATH, IMAGE_FOLDER)

# Example one for text search
print("="*60)
print("Example 1: Text-to-Image Search")
print("="*60 + "\n")

text_queries = [
    "a cat sitting on a chair",
    "sunset over the ocean",
    "people walking in a city street"
]

for query in text_queries:
    print(f"Query: '{query}'")
    results = search_by_text(query, top_k=3)
    print("Results:")
    for rank, (image_name, score) in enumerate(results, 1):
        print(f"  {rank}. {image_name} - Score: {score:.4f}")
    print()

# Example two for image search
print("="*60)
print("Example 2: Image-to-Image Search")
print("="*60 + "\n")
# Using the first image for search
sample_image = os.path.join(IMAGE_FOLDER, image_names[0])

print(f"Query image: {image_names[0]}")
results = search_by_image(sample_image, top_k=5)
print("Similar images:")
for rank, (image_name, score) in enumerate(results, 1):
    print(f"  {rank}. {image_name} - Score: {score:.4f}")
print()

# Example three, system evaluation
evaluate_system(num_samples=3)

# Example four: displaying the results
print("\n" + "="*60)
print("Visual Display Examples")
print("="*60 + "\n")

# Displaying text
query_text = "a beautiful landscape"
print(f"Displaying results for: '{query_text}'")
results = search_by_text(query_text, top_k=3)
display_results(query_text, results, IMAGE_FOLDER)

# Displaying image
if len(image_names) > 2:
    query_img = os.path.join(IMAGE_FOLDER, image_names[2])
    print(f"\nDisplaying similar images for: {image_names[2]}")
    results = search_by_image(query_img, top_k=3)
    display_results(query_img, results, IMAGE_FOLDER)

# Additional examples for test
print("\n" + "="*60)
print("Additional Test Queries")
print("="*60 + "\n")

# Test with queries
test_queries = [
    "a dog playing in the park",
    "modern architecture building",
    "food on a plate",
    "nature and trees"
]

for query in test_queries:
    results = search_by_text(query, top_k=2)
    print(f"'{query}' -> {results[0][0]} ({results[0][1]:.3f})")

# Example: Test multiple images from URLs
print("\n" + "="*60)
print("Example: Batch Testing with Multiple Images from URLs")
print("="*60 + "\n")

import urllib.request
import time

# List of test image URLs (you can add more)
test_urls = [
    {
        "url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
        "description": "Mountain landscape"
    },
    {
        "url": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97",
        "description": "Person with laptop"
    },
    {
        "url": "https://images.unsplash.com/photo-1519681393784-d120267933ba",
        "description": "Mountain peak"
    },
    {
        "url": "https://unsplash.com/photos/group-of-people-walking-on-pedestrian-lane-PMxT0XtQ--A",
        "description": "People"
    },
    {
        "url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        "description": "Shoes and fashion items"
    }
]

# Test each URL
for idx, test_item in enumerate(test_urls, 1):
    print(f"\n{'='*60}")
    print(f"Test {idx}/{len(test_urls)}: {test_item['description']}")
    print(f"{'='*60}")

    url = test_item['url']
    test_image_path = f"/content/test_image_{idx}.jpg"

    try:
        # Download image
        print(f"Downloading: {url[:50]}...")
        urllib.request.urlretrieve(url, test_image_path)
        print(f"✓ Downloaded successfully\n")

        # Search by image
        print("Image-to-Image Search Results:")
        results = search_by_image(test_image_path, top_k=3)
        for rank, (image_name, score) in enumerate(results, 1):
            print(f"  {rank}. {image_name} - Score: {score:.4f}")

        # Search by text (using the description)
        print(f"\nText-to-Image Search for '{test_item['description']}':")
        text_results = search_by_text(test_item['description'], top_k=3)
        for rank, (image_name, score) in enumerate(text_results, 1):
            print(f"  {rank}. {image_name} - Score: {score:.4f}")

        # Display visual comparison
        print(f"\nVisual Results:")
        display_results(test_image_path, results, IMAGE_FOLDER)

        # Small delay to avoid overwhelming the output
        time.sleep(1)

    except Exception as e:
        print(f"✗ Error processing this image: {e}")
        continue

print("\n" + "="*60)
print("Batch Testing Complete!")
print("="*60)

