# -*- coding: utf-8 -*-
"""VLM_CLIP_Image_Similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCE6qUqR33Za_fRflMO_Hj3nPOAjiwMK

**Practice One, Chapter One: Image Similarity**

1. Imports
"""

# Import necessary libraries
import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import numpy as np
import os

"""2. Introducing model"""

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

"""3. Creating folders. Uploading to googlr colab"""

image_folder = "/content/images"  # images folder on google colab
image_embeddings_list = []
image_names = []

"""4. Create embeddings(step 3 of practice)"""

for img_name in os.listdir(image_folder):
    if img_name.endswith(('.jpg', '.jpeg', '.png')):
        img_path = os.path.join(image_folder, img_name)
        image = Image.open(img_path).convert('RGB')
        inputs = processor(images=image, return_tensors="pt")

        with torch.no_grad():
            embeddings = model.get_image_features(**inputs)

        embeddings = embeddings / embeddings.norm(dim=-1, keepdim=True)
        image_embeddings_list.append(embeddings.cpu().numpy())
        image_names.append(img_name)
        print(f"✓ {img_name}")

"""5. Search function"""

def search_similar(query_path, top_k=3):
    """Find top-k similar images"""
    image = Image.open(query_path).convert('RGB')
    inputs = processor(images=image, return_tensors="pt")

    with torch.no_grad():
        query_emb = model.get_image_features(**inputs)

    query_emb = query_emb / query_emb.norm(dim=-1, keepdim=True)
    query_emb = query_emb.cpu().numpy()

    all_emb = np.vstack(image_embeddings_list)
    sims = cosine_similarity(query_emb, all_emb)[0]
    top_idx = np.argsort(sims)[::-1][:top_k]

    return [(image_names[i], sims[i]) for i in top_idx]

"""6. Result function. Visualize Results"""

#query_path = "/content/query/car_red_9.jpg"  # test image

def show_results(query_path, top_k=3):
    """Display query and similar images"""
    results = search_similar(query_path, top_k)

    fig, axes = plt.subplots(1, top_k + 1, figsize=(16, 4))

    # Query image
    query_img = Image.open(query_path)
    axes[0].imshow(query_img)
    axes[0].set_title("Query", fontsize=14, weight='bold')
    axes[0].axis('off')

    # Similar images
    for i, (name, score) in enumerate(results, 1):
        img = Image.open(os.path.join(image_folder, name))
        axes[i].imshow(img)
        axes[i].set_title(f"{name}\n{score*100:.1f}%", fontsize=12)
        axes[i].axis('off')

    plt.tight_layout()
    plt.show()

    # Print results
    print("Top matches:")
    for i, (name, score) in enumerate(results, 1):
        print(f"{i}. {name}: {score*100:.1f}%")

"""7. Tests: for 4 types of images"""

query_image = "/content/query/car_blue_ref.jpg"  # test image 1
show_results(query_image, top_k=3)

query_image = "/content/query/chair_brown_ref.jpg"  #  test image 2
show_results(query_image, top_k=3)

query_image = "/content/query/bird_colored_ref.jpg"  #  test image 3
show_results(query_image, top_k=3)

query_image = "/content/query/dog_brown_ref.jpg"  #  test image 4
show_results(query_image, top_k=3)