# -*- coding: utf-8 -*-
"""VLM_Final_Project_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoBfGwZcAFVf3c8ElEgIKALD6DZyj52D

# VLM, Final Project: Simple Multimodal RAG

# Used paper:
Attention Is All You Need
https://arxiv.org/pdf/1706.03762

# Inatallations
"""

!pip install -q langchain pypdf faiss-cpu sentence-transformers
!pip install -q transformers accelerate bitsandbytes
!pip install -q pymupdf pillow pandas
!pip install -q -U langchain-community

"""# Imports"""

from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
from transformers import BitsAndBytesConfig
from transformers import AutoProcessor, AutoModelForVision2Seq
from transformers import BitsAndBytesConfig
import torch
import fitz  # PyMuPDF
from PIL import Image
import io
import pandas as pd
import re
from typing import List, Dict, Tuple
import numpy as np

""" # Load model"""

def load_qwen_model():
    """
    Load Qwen2.5-VL-3B-Instruct with 4-bit quantization
    This single model handles BOTH vision and text generation
    """
    print(" Loading Qwen2.5-VL-3B model...")
    print("   This will take 2-3 minutes on first run...")

    model_name = "Qwen/Qwen2.5-VL-3B-Instruct"

    # 4-bit quantization for Colab
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4"
    )

    # Load model
    from transformers import AutoModelForVision2Seq

    model = AutoModelForVision2Seq.from_pretrained(
        model_name,
        dtype=torch.float16,
        device_map="auto",
        quantization_config=bnb_config
    )

    # Load processor
    processor = AutoProcessor.from_pretrained(
        model_name,
        trust_remote_code=True
    )

    print(" Model loaded successfully!")
    print(f"   Memory usage: ~2-3 GB VRAM")

    return model, processor

"""# EXTRACT IMAGES FROM PDF"""

def extract_images_from_pdf(pdf_path: str, page_numbers: List[int]) -> List[Dict]:
    """
    Extract actual image data from PDF pages
    Returns list of dictionaries with image data
    """
    print(f"\n Extracting images from pages {page_numbers}...")

    doc = fitz.open(pdf_path)
    extracted_images = []

    for page_num in page_numbers:
        page = doc.load_page(page_num - 1)  # fitz uses 0-based indexing
        image_list = page.get_images(full=True)

        for img_idx, img in enumerate(image_list):
            try:
                xref = img[0]
                base_image = doc.extract_image(xref)
                image_bytes = base_image["image"]

                # Convert to PIL Image
                image = Image.open(io.BytesIO(image_bytes))

                # Convert to RGB if needed
                if image.mode != 'RGB':
                    image = image.convert('RGB')

                extracted_images.append({
                    'page': page_num,
                    'image_index': img_idx,
                    'image': image,
                    'size': image.size
                })

                print(f"   ✓ Page {page_num}, Image {img_idx + 1}: {image.size}")

            except Exception as e:
                print(f"   Could not extract image {img_idx + 1} on page {page_num}: {e}")

    doc.close()
    print(f"   Total images extracted: {len(extracted_images)}")
    return extracted_images

def analyze_image_with_qwen(image: Image, model, processor, prompt: str) -> str:
    """
    Use Qwen2.5-VL to understand image content
    Can extract text, describe diagrams, understand charts, etc.
    """
    # Prepare messages for Qwen2.5
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image},
                {"type": "text", "text": prompt}
            ]
        }
    ]

    # Prepare inputs
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    inputs = processor(
        text=[text],
        images=[image],
        padding=True,
        return_tensors="pt"
    ).to(model.device)

    # Generate response
    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=512,
            do_sample=False
        )

    # Decode output - simplified for Qwen2.5
    generated_ids = output_ids[:, inputs.input_ids.shape[1]:]

    output_text = processor.batch_decode(
        generated_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False
    )[0]

    return output_text

def process_all_images(images: List[Dict], model, processor) -> List[Dict]:
    """
    Process all extracted images with multiple prompts
    """
    print(f"\n Analyzing {len(images)} images with Qwen vision model...")

    analyzed_images = []

    for img_data in images:
        print(f"\n   Processing image {img_data['image_index'] + 1} on page {img_data['page']}...")

        # Multiple prompts to extract comprehensive information
        prompts = {
            'description': "Describe this image in detail. What does it show? Include any text, labels, numbers, or data visible.",
            'text_extraction': "Extract ALL text visible in this image, including labels, titles, axis labels, and any annotations.",
            'scientific_content': "If this is a scientific figure (chart, graph, diagram, table, formula), explain what it represents and what data or information it contains."
        }

        analysis = {
            'page': img_data['page'],
            'image_index': img_data['image_index'],
            'size': img_data['size']
        }

        for key, prompt in prompts.items():
            try:
                response = analyze_image_with_qwen(img_data['image'], model, processor, prompt)
                analysis[key] = response
                print(f"      ✓ {key}: {response[:80]}...")
            except Exception as e:
                analysis[key] = f"Error: {e}"
                print(f"      ✗ {key}: Error - {e}")

        # Create combined description
        combined = f"""
IMAGE {img_data['image_index'] + 1} on Page {img_data['page']}:

Description: {analysis['description']}

Text Content: {analysis['text_extraction']}

Scientific Analysis: {analysis['scientific_content']}
"""
        analysis['combined_text'] = combined.strip()
        analyzed_images.append(analysis)

    print(f"\n Completed image analysis")
    return analyzed_images

"""# EXTRACT TABLES"""

def extract_tables_from_pdf(pdf_path: str, page_numbers: List[int]) -> List[Dict]:
    """
    Extract tables with full content using PyMuPDF
    """
    print(f"\n Extracting tables from pages {page_numbers}...")

    doc = fitz.open(pdf_path)
    tables_data = []

    for page_num in page_numbers:
        page = doc.load_page(page_num - 1)
        tables = page.find_tables()

        if tables.tables:
            print(f"   Page {page_num}: Found {len(tables.tables)} table(s)")

            for table_idx, table in enumerate(tables.tables):
                try:
                    # Convert to pandas DataFrame
                    df = table.to_pandas()

                    # Create structured text representation
                    table_text = f"""
TABLE {table_idx + 1} on Page {page_num}:
Dimensions: {df.shape[0]} rows × {df.shape[1]} columns
Columns: {', '.join([str(col) for col in df.columns])}

Content:
{df.to_string(index=False)}
"""

                    tables_data.append({
                        'page': page_num,
                        'table_index': table_idx,
                        'dataframe': df,
                        'text_representation': table_text.strip(),
                        'shape': df.shape
                    })

                    print(f"       Table {table_idx + 1}: {df.shape[0]}×{df.shape[1]}")

                except Exception as e:
                    print(f"       Error extracting table {table_idx + 1}: {e}")

    doc.close()
    print(f"   Total tables extracted: {len(tables_data)}")
    return tables_data

"""# EXTRACT FORMULAS FROM TEXT"""

def extract_formulas_from_text(text: str) -> List[str]:
    """
    Extract mathematical formulas using regex patterns
    """
    patterns = [
        r'\$\$[^$]+\$\$',                      # Display math: $$...$$
        r'\$[^$]+\$',                          # Inline math: $...$
        r'\\begin\{equation\}.*?\\end\{equation\}',  # LaTeX equation
        r'\\begin\{align\}.*?\\end\{align\}',        # LaTeX align
        r'\\\[.*?\\\]',                        # Display: \[...\]
        r'\\\(.*?\\\)',                        # Inline: \(...\)
        r'[a-zA-Z]\s*=\s*[^,;\n]+',           # Simple equations
        r'∫|∑|∏|∂|∇|√|≈|≤|≥|±|×|÷',          # Math symbols
    ]

    formulas = []
    for pattern in patterns:
        matches = re.findall(pattern, text, re.DOTALL)
        formulas.extend(matches)

    # Remove duplicates, keep order
    seen = set()
    unique_formulas = []
    for f in formulas:
        f_clean = f.strip()
        if f_clean and f_clean not in seen and len(f_clean) > 2:
            seen.add(f_clean)
            unique_formulas.append(f_clean)

    return unique_formulas

"""# INTEGRATE EVERYTHING - BUILD ENHANCED DOCUMENTS"""

def build_enhanced_documents(pdf_path: str, page_numbers: List[int],
                            model, processor) -> List:

    print("\n" + "="*70)
    print("BUILDING ENHANCED MULTIMODAL DOCUMENTS")
    print("="*70)

    # 1. Load base text
    print("\n[1/4] Loading PDF text...")
    loader = PyPDFLoader(pdf_path)
    documents = loader.load()

    # 2. Extract and analyze images
    print("\n[2/4] Processing images...")
    images = extract_images_from_pdf(pdf_path, page_numbers)
    if images:
        analyzed_images = process_all_images(images, model, processor)
    else:
        analyzed_images = []
        print("   No images found")

    # 3. Extract tables
    print("\n[3/4] Extracting tables...")
    tables = extract_tables_from_pdf(pdf_path, page_numbers)

    # 4. Extract formulas
    print("\n[4/4] Extracting formulas...")
    doc_fitz = fitz.open(pdf_path)
    formulas_by_page = {}
    for page_num in page_numbers:
        page = doc_fitz.load_page(page_num - 1)
        page_text = page.get_text()
        formulas = extract_formulas_from_text(page_text)
        if formulas:
            formulas_by_page[page_num] = formulas
            print(f"   Page {page_num}: {len(formulas)} formulas")
    doc_fitz.close()

    # 5. Enhance documents
    print("\n[5/5] Combining all content...")
    enhanced_docs = []

    for doc in documents:
        page_num = int(doc.metadata['page']) + 1

        if page_num in page_numbers:
            enhanced_text = doc.page_content

            # Add image analysis
            page_images = [img for img in analyzed_images if img['page'] == page_num]
            if page_images:
                enhanced_text += "\n\n" + "="*50
                enhanced_text += "\n IMAGES ON THIS PAGE \n"
                enhanced_text += "="*50 + "\n"
                for img in page_images:
                    enhanced_text += "\n" + img['combined_text'] + "\n"

            # Add table content
            page_tables = [tbl for tbl in tables if tbl['page'] == page_num]
            if page_tables:
                enhanced_text += "\n\n" + "="*50
                enhanced_text += "\n TABLES ON THIS PAGE \n"
                enhanced_text += "="*50 + "\n"
                for tbl in page_tables:
                    enhanced_text += "\n" + tbl['text_representation'] + "\n"

            # Add formulas
            if page_num in formulas_by_page:
                enhanced_text += "\n\n" + "="*50
                enhanced_text += "\n FORMULAS ON THIS PAGE \n"
                enhanced_text += "="*50 + "\n"
                for i, formula in enumerate(formulas_by_page[page_num]):
                    enhanced_text += f"Formula {i+1}: {formula}\n"

            doc.page_content = enhanced_text
            enhanced_docs.append(doc)

    print(f"\n Enhanced {len(enhanced_docs)} documents")
    return enhanced_docs

"""# BUILD RAG SYSTEM (Vector Store + Retrieval)"""

def build_vector_store(documents: List) -> tuple:
    """
    Create FAISS vector store from documents
    """
    print("\n Building vector store...")

    # Split into chunks
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len
    )
    chunks = text_splitter.split_documents(documents)
    print(f"   Created {len(chunks)} chunks")

    # Create embeddings and vector store
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )
    vectorstore = FAISS.from_documents(chunks, embeddings)

    print(" Vector store ready")
    return vectorstore, embeddings



"""# QUESTION ANSWERING WITH QWEN"""

def answer_question(question: str, vectorstore, model, processor, k: int = 3) -> Dict:

    # Retrieve relevant documents
    retriever = vectorstore.as_retriever(search_kwargs={"k": k})

    #relevant_docs = retriever.get_relevant_documents(question)
    relevant_docs = retriever.invoke(question)

    # Combine context
    context = "\n\n---\n\n".join([doc.page_content for doc in relevant_docs])

    # Create prompt for Qwen
    prompt = f"""You are a scientific research assistant. Answer the question based ONLY on the provided context from a research paper.

Context:
{context}

Question: {question}

Instructions:
- Answer based strictly on the context provided
- If the context mentions images, tables, or formulas, reference them in your answer
- If you cannot find the answer in the context, say "I cannot find this information in the provided context"
- Be precise and concise

Answer:"""

    # Generate answer with Qwen
    messages = [{"role": "user", "content": prompt}]
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    inputs = processor(
        text=[text],
        padding=True,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=512,
            do_sample=True,
            temperature=0.3
        )

    generated_ids = [
        output_ids[len(input_ids):]
        for input_ids, output_ids in zip(inputs.input_ids, output_ids)
    ]

    answer = processor.batch_decode(
        generated_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False
    )[0]

    return {
        'question': question,
        'answer': answer,
        'context': context,
        'num_sources': len(relevant_docs),
        'sources': relevant_docs
    }


def print_answer(result: Dict):
    """Pretty print Q&A result"""
    print("\n" + "="*70)
    print(f" QUESTION: {result['question']}")
    print("="*70)
    print(f"\n ANSWER:\n{result['answer']}")
    print(f"\n Sources used: {result['num_sources']}")

    for i, doc in enumerate(result['sources']):
        page = int(doc.metadata.get('page', -1)) + 1
        preview = doc.page_content[:150].replace('\n', ' ')
        print(f"   [{i+1}] Page {page}: {preview}...")
    print("="*70)

"""# EVALUATION FUNCTIONS"""

def evaluate_system(vectorstore, model, processor, test_questions: List[str]) -> Dict:

    print("\n" + "="*70)
    print("SYSTEM EVALUATION")
    print("="*70)

    results = []

    for i, question in enumerate(test_questions, 1):
        print(f"\n[{i}/{len(test_questions)}] Testing: {question}")
        try:
            result = answer_question(question, vectorstore, model, processor)
            results.append(result)
            print(f"   ✓ Answer generated ({len(result['answer'])} chars)")
        except Exception as e:
            print(f"   ✗ Error: {e}")
            results.append({'question': question, 'answer': f'Error: {e}', 'num_sources': 0})

    # Calculate metrics
    avg_sources = np.mean([r['num_sources'] for r in results])
    successful = sum(1 for r in results if 'Error' not in r['answer'])

    metrics = {
        'total_questions': len(test_questions),
        'successful_answers': successful,
        'success_rate': successful / len(test_questions),
        'avg_sources_retrieved': avg_sources,
        'results': results
    }

    # Print summary
    print("\n" + "="*70)
    print("EVALUATION SUMMARY")
    print("="*70)
    print(f"Total questions: {metrics['total_questions']}")
    print(f"Successful: {metrics['successful_answers']} ({metrics['success_rate']*100:.1f}%)")
    print(f"Avg sources retrieved: {metrics['avg_sources_retrieved']:.1f}")
    print("="*70)

    return metrics


def print_detailed_evaluation(metrics: Dict):
    """Print detailed evaluation report"""
    print("\n" + "="*70)
    print("DETAILED EVALUATION REPORT")
    print("="*70)

    for i, result in enumerate(metrics['results'], 1):
        print(f"\n[Question {i}]")
        print(f"Q: {result['question']}")
        print(f"A: {result['answer'][:200]}...")
        print(f"Sources: {result['num_sources']}")
        print("-"*70)

"""# INTERACTIVE SESSION"""

def interactive_session(vectorstore, model, processor):
    """
    Run interactive Q&A session
    """
    print("\n" + "="*70)
    print(" INTERACTIVE Q&A SESSION")
    print("="*70)
    print("Type your questions about the paper.")
    print("Type 'exit' or 'quit' to end session.\n")

    while True:
        question = input("Your question: ").strip()

        if question.lower() in ['exit', 'quit', 'q']:
            print("\n Session ended. Goodbye!")
            break

        if not question:
            continue

        try:
            result = answer_question(question, vectorstore, model, processor)
            print_answer(result)
        except Exception as e:
            print(f"\n Error: {e}")

"""# Upload file"""

#pdf_path = "/content/2504.08748v1.pdf"
#pdf_path = "/content/2025-retrieval-augmented-multimodal-models-Paper-Conference.pdf"
pdf_path = "/content/1706.03762v7.pdf"
#target_pages = [1, 2, 3,6, 8,9,10,11, 17,18, 34, 39, 40, 41, 42]           # pages to analyze
target_pages = [1,2, 3, 4, 5, 6, 7, 8, 9, 10]
print("="*70)
print(" SIMPLE MULTIMODAL RAG SYSTEM")
print("   Using Qwen2.5-VL-3B-Instruct")
print("="*70)
print(f"\n PDF: {pdf_path}")
print(f" Pages: {target_pages}")

print("\n" + "="*70)
print("[STEP 1] Loading Qwen2.5-VL model...")
print("="*70)
#print("  This will take 2-3 minutes on first run...")

try:
    model, processor = load_qwen_model()
    print("\n  SUCCESS: Model loaded!")
except Exception as e:
    print(f"\n  ERROR: {e}")
    import traceback
    traceback.print_exc()

"""# PROCESS FILE"""

print("\n" + "="*70)
print("[STEP 2] Processing PDF with multimodal extraction...")
print("="*70)

try:
    documents = build_enhanced_documents(pdf_path, target_pages, model, processor)

    print(f"\n SUCCESS: {len(documents)} documents created!")

    # Preview first document
    if documents:
        print("\n Preview (first 500 chars):")
        print("-"*70)
        print(documents[0].page_content[:500] + "...")
        print("-"*70)

except Exception as e:
    print(f"\n ERROR: {e}")
    import traceback
    traceback.print_exc()

"""# BUILD VECTOR STORE"""

print("\n" + "="*70)
print("[STEP 3] Building Vector Store...")
print("="*70)

try:
    vectorstore, embeddings = build_vector_store(documents)
    print("\n SUCCESS: Vector store ready!")

except Exception as e:
    print(f"\n ERROR: {e}")
    import traceback
    traceback.print_exc()

"""# Test"""

# TEST SINGLE QUESTION

print("\n" + "="*70)
print("[STEP 4A] Testing with ONE question...")
print("="*70)

test_question = "What is the Transformer model?"

try:
    result = answer_question(test_question, vectorstore, model, processor)
    print_answer(result)
    print("\n SUCCESS: Single question works!")

except Exception as e:
    print(f"\n ERROR: {e}")
    import traceback
    traceback.print_exc()

# TEST MULTIPLE QUESTIONS (EVALUATION)
print("\n" + "="*70)
print("[STEP 4B] Evaluating with multiple questions...")
print("="*70)

test_questions = [
    "What are the main findings of this paper?",
    "Describe the images or figures in the paper",
    "What data is shown in the tables?",
    "What mathematical formulas are presented?",
    "What methods were used in this research?",
    "What BLEU scores are reported in the results tables?"
]

try:
    metrics = evaluate_system(vectorstore, model, processor, test_questions)
    print_detailed_evaluation(metrics)
    print("\n✅ SUCCESS: Evaluation complete!")

except Exception as e:
    print(f"\n❌ ERROR: {e}")
    import traceback
    traceback.print_exc()

# INTERACTIVE SESSION

print("\n" + "="*70)
print("[STEP 5] Interactive Q&A Session")
print("="*70)
print(" Run this cell when ready for interactive questions")
print("   Type 'exit' to quit")

try:
    interactive_session(vectorstore, model, processor)

except Exception as e:
    print(f"\n ERROR: {e}")
    import traceback
    traceback.print_exc()

"""SYSTEM EVALUATION AND ANALYSIS
================================

TESTING METHODOLOGY:
-------------------
- Models tested: 2 different models (Qwen2.5-VL-3B and Gemma3
- PDF files tested: 3 different scientific papers
- Approach: Iterative testing with function modifications and concept improvements
- Question types: Text, images, tables, and formulas

EVALUATION RESULTS:
------------------
✓ Answer Coherence: YES - Answers were logical and well-structured.
  When uncertain, the model appropriately stated "cannot find information"

✓ Content Referencing: YES - Model correctly retrieved and referenced
  relevant sections from the PDFs

✓ Multimodal Recognition: YES - Successfully identified and processed:
  - Images/figures (architecture diagrams, charts)
  - Tables (data extraction and interpretation)  
  - Formulas (mathematical notation)
  Each content type was recognized separately and appropriately

✓ Answer Accuracy: YES - Generally accurate based on PDF content
  Note: Some uncertainty observed with complex mathematical formulas

✓ Answer Completeness: YES - Responses were comprehensive and addressed
  the questions fully

QUALITY ASSESSMENT:
------------------
Overall quality distribution:
- Good quality: ~70% of cases
- Acceptable quality: ~25% of cases
- Poor quality: ~5% of cases

STRENGTHS IDENTIFIED:
--------------------
- Strong text comprehension and retrieval
- Effective image analysis using vision model
- Good table structure recognition
- Appropriate uncertainty handling
- Multimodal content integration

WEAKNESSES IDENTIFIED:
---------------------
- Formula extraction accuracy could be improved (regex patterns limitation)
- Complex mathematical notation sometimes unclear
- Performance varies by PDF structure/quality

IMPROVEMENTS MADE:
-----------------
- Optimized retrieval parameters (k value adjustment)
- Refined question phrasing for better results
- Enhanced prompts for vision model
- Modified processing functions for better content extraction

CONCLUSION:
----------
The Simple Multimodal RAG system successfully demonstrates the ability to:
1. Extract and process multimodal content (text, images, tables, formulas)
2. Retrieve relevant information using FAISS vector store
3. Generate accurate answers using Qwen2.5-VL-3B model
4. Handle various question types across different scientific papers

The system meets the project requirements with good overall performance,
though there is room for improvement in mathematical formula processing.

"""

